import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BookOpen, CircuitBoard, Eye, FlaskConical, Linkedin, Mail, Target } from "lucide-react";

import SectionHeading from "@/components/SectionHeading";

export const metadata: Metadata = { title: "About", description: "Why CoreSelva exists, who started it, and what it is building." };

const principles = [
  { icon: Eye, title: "Readable before clever", copy: "A design should expose its important decisions. Compact code is not useful education if the architecture disappears inside it." },
  { icon: FlaskConical, title: "Evidence before claims", copy: "Implemented, planned, and research work are labelled separately. Tests and measurements should define what a design can honestly claim." },
  { icon: BookOpen, title: "Depth without gatekeeping", copy: "Teaching can begin gently without becoming shallow. The path should take a newcomer from first principles to professional reasoning." },
];

export default function AboutPage() {
  return <div className="page-shell">
    <section className="relative overflow-hidden border-b border-white/10 py-24 sm:py-32"><div className="grid-noise absolute inset-0"/><div className="site-container relative"><p className="eyebrow">ABOUT CORESELVA</p><h1 className="display-title mt-5 max-w-5xl">Opening the machine, one understandable layer at a time.</h1><p className="body-copy mt-7 max-w-3xl">CoreSelva is an independent open-hardware and education initiative building RISC-V processor IP, SoC components, and serious engineering learning resources.</p></div></section>

    <section className="section-space"><div className="site-container grid gap-12 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="eyebrow">THE PEOPLE</p><div className="mt-7 space-y-4"><article className="panel flex items-center gap-5 p-5"><Image src="/karan.jpg" alt="Karan Arjun Selvan" width={64} height={64} className="h-16 w-16 rounded-full object-cover"/><div><p className="text-xs font-bold uppercase tracking-wider text-white/40">Maintainer and developer</p><h2 className="mt-1 text-xl font-black">Karan Arjun Selvan</h2><p className="mt-1 text-sm text-white/50">Mechatronics & Automation Engineering</p><div className="mt-3 flex flex-wrap gap-3"><a className="inline-flex items-center gap-1.5 text-sm font-bold text-yellow" href="mailto:karanarjun432@gmail.com"><Mail size={14}/>Email</a><a className="inline-flex items-center gap-1.5 text-sm font-bold text-yellow" href="https://www.linkedin.com/in/karanarjuns/" target="_blank" rel="noreferrer"><Linkedin size={14}/>LinkedIn</a></div></div></article><article className="panel flex items-center gap-5 p-5"><Image src="/vishal.jpg" alt="Vishal Selvan" width={64} height={64} className="h-16 w-16 rounded-full object-cover"/><div><p className="text-xs font-bold uppercase tracking-wider text-white/40">Co-developer</p><h2 className="mt-1 text-xl font-black">Vishal Selvan</h2><p className="mt-1 text-sm text-white/50">Electronics & Communication Engineering, SASTRA University</p><div className="mt-3 flex flex-wrap gap-3"><a className="inline-flex items-center gap-1.5 text-sm font-bold text-yellow" href="mailto:vishalselvan0017@gmail.com"><Mail size={14}/>Email</a><a className="inline-flex items-center gap-1.5 text-sm font-bold text-yellow" href="https://www.linkedin.com/in/vishal-selvan-252328285/" target="_blank" rel="noreferrer"><Linkedin size={14}/>LinkedIn</a></div></div></article></div></div><div className="space-y-6 text-base leading-8 text-white/65"><p>CoreSelva is developed by Karan Arjun Selvan and Vishal Selvan to create open processor cores while documenting the knowledge required to understand them.</p><p>The project grew from a simple problem: advanced computing systems are often taught as disconnected subjects. C programming, embedded firmware, digital logic, processor architecture, FPGA implementation, and verification may appear in different courses, but real hardware requires them to work together.</p><p>Together, Karan and Vishal are building CoreSelva as one coherent path: develop the hardware openly, explain the reasoning clearly, and keep the result available for others to inspect and extend.</p></div></div></section>

    <section className="section-space border-y border-white/10 bg-white/[0.018]"><div className="site-container"><SectionHeading eyebrow="WHY IT EXISTS" title="The gap is not a lack of information. It is a lack of connection." copy="CoreSelva exists to connect theory, implementation, and proof."/><div className="mt-12 grid gap-5 md:grid-cols-3">{principles.map(({icon: Icon, ...item}) => <article key={item.title} className="panel p-7"><Icon className="text-yellow" size={24}/><h2 className="mt-6 text-xl font-black">{item.title}</h2><p className="mt-3 text-sm leading-6 text-white/55">{item.copy}</p></article>)}</div></div></section>

    <section className="section-space"><div className="site-container grid gap-12 lg:grid-cols-2"><div className="panel p-8 sm:p-10"><CircuitBoard className="text-yellow" size={28}/><p className="eyebrow mt-7">WHAT WE DO</p><h2 className="mt-4 text-3xl font-black">Build open technical foundations.</h2><ul className="mt-7 space-y-4 text-sm leading-6 text-white/60"><li>Develop readable RV64 and RV32 RISC-V processor cores.</li><li>Create reusable peripherals for complete educational SoCs.</li><li>Publish architecture goals, maturity, limitations, and source.</li><li>Teach embedded C, hardware, RISC-V, FPGA design, and verification as connected skills.</li></ul></div><div className="panel p-8 sm:p-10"><Target className="text-yellow" size={28}/><p className="eyebrow mt-7">THE GOAL</p><h2 className="mt-4 text-3xl font-black">A complete open learning platform for computer systems.</h2><p className="mt-7 text-sm leading-7 text-white/60">The long-term goal is a family of understandable processor cores and SoC IP supported by curriculum, simulation, verification, FPGA examples, and practical documentation—from a beginner’s first C program to operating-system-capable RISC-V hardware.</p></div></div></section>

    <section className="pb-24"><div className="site-container"><div className="rounded-3xl bg-yellow p-8 text-black sm:p-12"><p className="text-xs font-black uppercase tracking-[0.2em]">EXPLORE THE WORK</p><h2 className="mt-3 max-w-3xl text-3xl font-black tracking-tight sm:text-4xl">See the hardware or begin with the foundations.</h2><div className="mt-8 flex flex-wrap gap-3"><Link href="/products" className="inline-flex items-center gap-2 rounded-xl bg-black px-5 py-3 text-sm font-extrabold text-white">Open IP catalogue <ArrowRight size={16}/></Link><Link href="/academy" className="inline-flex items-center gap-2 rounded-xl border border-black/25 px-5 py-3 text-sm font-extrabold">CoreSelva Academy</Link></div></div></div></section>
  </div>;
}
