"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

import { getSupabaseBrowserClient, isCommunityConfigured } from "@/lib/supabase/client";

function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "").slice(0, 72); }

export default function NewProjectForm() {
  const router = useRouter(); const [form, setForm] = useState({ title: "", summary: "", description: "", status: "building", technologies: "", repo_url: "", demo_url: "" }); const [status, setStatus] = useState("");
  const update = (key: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setForm(current => ({ ...current, [key]: event.target.value }));
  async function submit(event: React.FormEvent){event.preventDefault(); const supabase=getSupabaseBrowserClient(); if(!supabase){setStatus("Project publishing is in preview mode until Supabase is configured.");return} const {data:auth}=await supabase.auth.getUser(); if(!auth.user){setStatus("Sign in with GitHub before adding a project.");return} if(form.title.trim().length<4||form.summary.trim().length<20||form.description.trim().length<50){setStatus("Add a clear title, summary and a technical description of at least 50 characters.");return} const slug=`${slugify(form.title)}-${Date.now().toString(36)}`; const {error}=await supabase.from("projects").insert({author_id:auth.user.id,slug,title:form.title.trim(),summary:form.summary.trim(),description:form.description.trim(),status:form.status,technologies:form.technologies.split(",").map(v=>v.trim()).filter(Boolean).slice(0,10),repo_url:form.repo_url.trim()||null,demo_url:form.demo_url.trim()||null}); if(error){setStatus(error.message);return} router.push(`/projects/${slug}`);router.refresh()}
  return <form onSubmit={submit} className="panel p-6 sm:p-8"><div className="grid gap-6"><label className="grid gap-2"><span className="text-sm font-bold">Project title</span><input className="field" value={form.title} onChange={update("title")} maxLength={100} placeholder="A specific, memorable name"/></label><label className="grid gap-2"><span className="text-sm font-bold">One-sentence summary</span><input className="field" value={form.summary} onChange={update("summary")} maxLength={220} placeholder="What does it do, and what makes it technically useful?"/></label><div className="grid gap-6 sm:grid-cols-2"><label className="grid gap-2"><span className="text-sm font-bold">State</span><select className="field" value={form.status} onChange={update("status")}><option value="idea">Idea</option><option value="building">Building</option><option value="working">Working</option><option value="verified">Verified</option></select></label><label className="grid gap-2"><span className="text-sm font-bold">Technologies</span><input className="field" value={form.technologies} onChange={update("technologies")} placeholder="Embedded C, STM32, SPI"/></label></div><label className="grid gap-2"><span className="text-sm font-bold">Technical story</span><textarea className="field min-h-64 resize-y" value={form.description} onChange={update("description")} placeholder={'Goal and constraints:\n\nArchitecture:\n\nEvidence and current results:\n\nKnown limitations and next step:'}/></label><div className="grid gap-6 sm:grid-cols-2"><label className="grid gap-2"><span className="text-sm font-bold">Source repository</span><input type="url" className="field" value={form.repo_url} onChange={update("repo_url")} placeholder="https://github.com/…"/></label><label className="grid gap-2"><span className="text-sm font-bold">Demo or documentation</span><input type="url" className="field" value={form.demo_url} onChange={update("demo_url")} placeholder="https://…"/></label></div><div className="flex flex-col gap-3 border-t border-white/10 pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-white/40">{isCommunityConfigured()?"The project will appear on your public profile.":"Preview mode: configure Supabase before publishing."}</p><button className="button-primary" type="submit">Publish project</button></div>{status&&<p className="rounded-lg border border-yellow/20 bg-yellow/10 px-4 py-3 text-sm text-yellow">{status}</p>}</div></form>;
}
