"use client";

import Link from "next/link";
import { Github, Globe2, MessageSquareText } from "lucide-react";
import { useEffect, useState } from "react";

import Avatar from "@/components/Avatar";
import { demoPosts, demoProjects } from "@/lib/community-data";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import type { CommunityPost, Profile, Project } from "@/lib/types";

export default function ProfileView({ username }: { username: string }) {
  const demoProfile = [...demoPosts.map(item=>item.author),...demoProjects.map(item=>item.author)].find(item=>item.username===username) ?? { id:"preview", username, full_name:username, avatar_url:null, bio:"CoreSelva community member." };
  const [profile,setProfile]=useState<Profile>(demoProfile); const [posts,setPosts]=useState<CommunityPost[]>(demoPosts.filter(item=>item.author.username===username)); const [projects,setProjects]=useState<Project[]>(demoProjects.filter(item=>item.author.username===username));
  useEffect(()=>{const supabase=getSupabaseBrowserClient();if(!supabase)return;supabase.from("profiles").select("*").eq("username",username).single().then(async({data})=>{if(!data)return;setProfile(data as Profile);const [postResult,projectResult]=await Promise.all([supabase.from("posts").select("*, author:profiles!posts_author_id_fkey(*)").eq("author_id",data.id).order("created_at",{ascending:false}),supabase.from("projects").select("*, author:profiles!projects_author_id_fkey(*)").eq("author_id",data.id).order("created_at",{ascending:false})]);if(postResult.data)setPosts(postResult.data as unknown as CommunityPost[]);if(projectResult.data)setProjects(projectResult.data as unknown as Project[])})},[username]);
  return <div><section className="panel overflow-hidden"><div className="h-32 border-b border-yellow/15 bg-[radial-gradient(circle_at_20%_0%,rgba(255,210,10,.18),transparent_55%)]"/><div className="px-6 pb-7 sm:px-8"><div className="-mt-10 flex flex-col gap-5 sm:flex-row sm:items-end"><Avatar name={profile.username} src={profile.avatar_url} size="lg"/><div className="flex-1"><h1 className="text-3xl font-black">{profile.full_name??profile.username}</h1><p className="mt-1 text-sm text-yellow">@{profile.username}</p></div><div className="flex gap-2">{profile.github_url&&<a className="button-quiet" href={profile.github_url} target="_blank" rel="noreferrer"><Github size={15}/>GitHub</a>}{profile.website&&<a className="button-quiet" href={profile.website} target="_blank" rel="noreferrer"><Globe2 size={15}/>Website</a>}</div></div><p className="mt-6 max-w-2xl text-sm leading-6 text-white/55">{profile.bio??"This member has not added a bio yet."}</p><div className="mt-6 flex gap-6 border-t border-white/10 pt-5 text-xs"><span><b className="text-lg text-white">{projects.length}</b><small className="ml-2 text-white/35">projects</small></span><span><b className="text-lg text-white">{posts.length}</b><small className="ml-2 text-white/35">discussions</small></span></div></div></section><div className="mt-10 grid gap-8 lg:grid-cols-2"><section><h2 className="text-xl font-black">Projects</h2><div className="mt-4 grid gap-3">{projects.map(project=><Link key={project.id} href={`/projects/${project.slug}`} className="panel panel-hover p-5"><span className="tag capitalize">{project.status}</span><h3 className="mt-3 font-black">{project.title}</h3><p className="mt-2 text-sm leading-6 text-white/45">{project.summary}</p></Link>)}{!projects.length&&<div className="panel p-6 text-sm text-white/35">No public projects yet.</div>}</div></section><section><h2 className="text-xl font-black">Discussions</h2><div className="mt-4 grid gap-3">{posts.map(post=><Link key={post.id} href={`/community/${post.slug}`} className="panel panel-hover p-5"><span className="tag">{post.category}</span><h3 className="mt-3 font-black">{post.title}</h3><span className="mt-3 flex items-center gap-1 text-xs text-white/35"><MessageSquareText size={13}/>{post.reply_count} replies</span></Link>)}{!posts.length&&<div className="panel p-6 text-sm text-white/35">No public discussions yet.</div>}</div></section></div></div>;
}
