"use client";

import { useEffect, useState } from "react";

import Avatar from "@/components/Avatar";
import { formatRelativeDate } from "@/lib/community-data";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import type { Profile } from "@/lib/types";

type ProjectComment = { id: string; project_id: string; parent_id: string | null; body: string; created_at: string; author: Profile };

export default function ProjectComments({ projectId }: { projectId: string }) {
  const [comments, setComments] = useState<ProjectComment[]>([]); const [body,setBody]=useState(""); const [replyTo,setReplyTo]=useState<string|null>(null); const [status,setStatus]=useState("");
  useEffect(()=>{const supabase=getSupabaseBrowserClient();if(!supabase||projectId.startsWith("project-"))return;supabase.from("project_comments").select("*, author:profiles!project_comments_author_id_fkey(*)").eq("project_id",projectId).order("created_at").then(({data})=>{if(data)setComments(data as unknown as ProjectComment[])})},[projectId]);
  async function publish(event:React.FormEvent){event.preventDefault();const supabase=getSupabaseBrowserClient();if(!supabase||projectId.startsWith("project-")){setStatus("Project comments become live after Supabase is configured.");return}const{data:auth}=await supabase.auth.getUser();if(!auth.user){setStatus("Sign in with GitHub before commenting.");return}if(body.trim().length<8){setStatus("Add a little more reasoning before publishing.");return}const{data,error}=await supabase.from("project_comments").insert({project_id:projectId,author_id:auth.user.id,parent_id:replyTo,body:body.trim()}).select("*, author:profiles!project_comments_author_id_fkey(*)").single();if(error){setStatus(error.message);return}if(data)setComments(current=>[...current,data as unknown as ProjectComment]);setBody("");setReplyTo(null);setStatus("Comment published.")}
  const renderComment=(comment:ProjectComment,nested=false)=><article key={comment.id} className={`${nested?"ml-8 border-l border-yellow/20 pl-5":""} py-5`}><div className="flex gap-3"><Avatar name={comment.author.username} src={comment.author.avatar_url} size="sm"/><div><div className="text-xs"><b className="text-white/70">@{comment.author.username}</b><span className="ml-2 text-white/30">{formatRelativeDate(comment.created_at)}</span></div><p className="mt-3 text-sm leading-7 text-white/60">{comment.body}</p><button onClick={()=>setReplyTo(comment.id)} className="mt-2 text-xs font-bold text-white/35 hover:text-yellow">Reply</button></div></div></article>;
  return <section className="mt-16 border-t border-white/10 pt-10"><h2 className="text-2xl font-black">Project discussion</h2><p className="mt-2 text-sm text-white/45">Review architecture and evidence. Keep preference separate from requirement.</p><div className="mt-6 divide-y divide-white/10">{comments.filter(item=>!item.parent_id).map(comment=><div key={comment.id}>{renderComment(comment)}{comments.filter(item=>item.parent_id===comment.id).map(child=>renderComment(child,true))}</div>)}{!comments.length&&<p className="py-8 text-sm text-white/35">No comments yet. Ask the first technical question.</p>}</div><form onSubmit={publish} className="panel mt-5 p-5"><div className="flex items-center justify-between"><b className="text-sm">{replyTo?"Reply to comment":"Add a comment"}</b>{replyTo&&<button type="button" onClick={()=>setReplyTo(null)} className="text-xs text-white/35 hover:text-yellow">Cancel reply</button>}</div><textarea className="field mt-4 min-h-28 resize-y" value={body} onChange={event=>setBody(event.target.value)} placeholder="What did you understand, question, measure or suggest?"/><div className="mt-3 flex justify-end"><button className="button-primary" type="submit">Publish comment</button></div>{status&&<p className="mt-3 text-xs text-yellow">{status}</p>}</form></section>;
}
