import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpenCheck, Clock3, Cpu, Gauge, Layers3, ListChecks } from "lucide-react";

import SectionHeading from "@/components/SectionHeading";

export const metadata: Metadata = { title: "Academy", description: "Professional, zero-to-advanced embedded systems learning from CoreSelva." };

const tracks = [
  { icon: ListChecks, title: "Embedded C — 129-topic roadmap", level: "Guided reference", lessons: "15 phases · 129 topics", copy: "The complete supplied roadmap: C foundations, pointers, memory, bit operations, drivers, build systems, STM32 register work, VS Code debugging, interview topics, and a 30-day practice plan.", href: "/academy/embedded-c-roadmap/index.html", live: true },
  { icon: Cpu, title: "RISC-V architecture", level: "Foundation to pipeline", lessons: "In development", copy: "Instruction execution, datapaths, control, hazards, privilege and verification using readable CoreSelva cores.", href: "#roadmap", live: false },
  { icon: Layers3, title: "FPGA design practice", level: "Project based", lessons: "Planned", copy: "Simulation-first RTL, constraints, timing, board bring-up and evidence-driven debugging.", href: "#roadmap", live: false },
];

export default function AcademyPage() {
  return (
    <div className="page-shell">
      <section className="relative overflow-hidden border-b border-white/10 py-24 sm:py-32"><div className="grid-noise absolute inset-0"/><div className="site-container relative"><div className="max-w-4xl"><p className="eyebrow">CORESELVA ACADEMY</p><h1 className="display-title mt-5">A serious path into embedded systems—without assuming you already belong.</h1><p className="body-copy mt-7 max-w-2xl">We begin before the first line of C, build exact mental models, and keep going until you can reason about hardware, timing, failures and product constraints professionally.</p><div className="mt-9 flex flex-wrap gap-3"><a className="button-primary" href="/academy/embedded-c-roadmap/index.html">Open the 129-topic Embedded C course <ArrowRight size={16}/></a><Link className="button-secondary" href="/products">Explore open IP</Link></div></div></div></section>

      <section className="section-space"><div className="site-container"><SectionHeading eyebrow="LEARNING TRACKS" title="Start gently. Finish technically dangerous—in the good way." copy="Every track uses definitions, worked examples, failure cases, practice and explanation checks instead of overview-only content."/><div className="mt-12 grid gap-5 lg:grid-cols-3">{tracks.map(({icon: Icon,...track}) => <article key={track.title} className="panel panel-hover flex flex-col p-7"><span className="grid h-12 w-12 place-items-center rounded-xl border border-yellow/20 bg-yellow/10 text-yellow"><Icon size={22}/></span><div className="mt-6 flex items-center gap-2 text-[11px] font-bold uppercase tracking-wider"><span className="text-yellow">{track.level}</span><span className="text-white/20">•</span><span className="text-white/40">{track.lessons}</span></div><h2 className="mt-3 text-2xl font-black">{track.title}</h2><p className="mt-4 text-sm leading-6 text-white/50">{track.copy}</p><div className="mt-auto pt-7">{track.live ? <a className="button-primary w-full" href={track.href}>Begin course <ArrowRight size={16}/></a> : <span className="flex w-full justify-center rounded-xl border border-white/10 py-3 text-sm font-bold text-white/30">Curriculum in development</span>}</div></article>)}</div></div></section>

      <section className="section-space border-y border-white/10 bg-white/[0.018]"><div className="site-container grid gap-12 lg:grid-cols-[0.85fr_1.15fr]"><div><p className="eyebrow">HOW A LESSON WORKS</p><h2 className="section-title mt-4">Understanding is an observable skill.</h2><p className="body-copy mt-5">A lesson is complete when you can predict, trace, explain and transfer the idea—not when you reach the bottom of a page.</p></div><div className="grid gap-4 sm:grid-cols-2">{[[BookOpenCheck,"Model","Build the exact idea and vocabulary before memorizing syntax."],[Clock3,"Trace","Walk through control flow, values, state and time in order."],[Gauge,"Measure","Use diagnostics, tests, waveforms and budgets as evidence."],[ArrowRight,"Transfer","Apply the idea to a new boundary case or real subsystem."]].map(([Icon,title,copy]) => { const LessonIcon = Icon as typeof BookOpenCheck; return <div key={String(title)} className="panel p-6"><LessonIcon size={19} className="text-yellow"/><h3 className="mt-4 font-black">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-white/50">{String(copy)}</p></div>; })}</div></div></section>

      <section id="roadmap" className="section-space"><div className="site-container"><SectionHeading eyebrow="ACADEMY ROADMAP" title="One coherent engineering curriculum" copy="The public roadmap grows outward from C and hardware fundamentals. Each phase keeps the sequence deliberate, the examples practical, and the technical depth intact."/><div className="mt-12 overflow-hidden rounded-2xl border border-white/10"><div className="grid grid-cols-[80px_1fr] border-b border-white/10 bg-yellow px-5 py-3 text-xs font-black uppercase tracking-wider text-black sm:grid-cols-[130px_1fr_180px]"><span>Phase</span><span>Track</span><span className="hidden sm:block">State</span></div>{[["01","Embedded C and firmware","Published"],["02","Digital logic and RISC-V","Authoring"],["03","FPGA implementation","Planned"],["04","Verification and SoC integration","Planned"],["05","Production embedded systems","Curriculum research"]].map(([phase,title,state]) => <div key={phase} className="grid grid-cols-[80px_1fr] border-b border-white/10 px-5 py-5 last:border-0 sm:grid-cols-[130px_1fr_180px]"><span className="font-mono text-xs text-yellow">{phase}</span><span className="text-sm font-bold">{title}</span><span className="hidden text-xs text-white/40 sm:block">{state}</span></div>)}</div></div></section>
    </div>
  );
}
